# Build
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

# Serve con Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
RUN printf "server { \
  listen 80; \
  server_name _; \
  location / { try_files \$uri /index.html; } \
} " > /etc/nginx/conf.d/default.conf
EXPOSE 80
